language: cpp
sudo: required
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
            - libgtest-dev
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
          packages:
            - clang-3.6
            - cmake
            - cmake-data
            - libgtest-dev
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
          packages:
            - clang-3.7
            - cmake
            - cmake-data
            - libgtest-dev
      env: COMPILER=clang++-3.7

script:
  - install -d build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DENABLE_TESTING=ON -DENABLE_TRAVIS=ON ..
  - make VERBOSE=1
  - make test